# Path related
raw_dataset_dir: data/raw/
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl
train_feng_set_path:
- data/processed/x_train_feng.pkl
- data/processed/y_train_feng.pkl
valid_feng_set_path:
- data/processed/x_valid_feng.pkl
- data/processed/y_valid_feng.pkl
test_feng_set_path:
- data/processed/x_test_feng.pkl
- data/processed/y_test_feng.pkl
raw_dataset_path: data/processed/raw_dataset.pkl
cleaned_raw_dataset_path: data/processed/raw_dataset.pkl
production_model_path: C:\File\pacmann\project\Hotel2\models\production_model.pkl
ohe_room_path: C:\File\pacmann\project\Hotel2\models\ohe_room.pkl
le_encoder_path: C:\File\pacmann\project\Hotel2\models\le_encoder.pkl
training_log_path: log/training_log.json

# Debug related
print_debug: true

# Columns by data type related
int32_columns:
- no_of_adults
- no_of_children
- no_of_weekend_nights
- no_of_week_nights
- required_car_parking_space
- lead_time
- arrival_year
- arrival_month
- arrival_date
- repeated_guest
- no_of_previous_cancellations
- no_of_previous_bookings_not_canceled
- no_of_special_requests
- avg_price_per_room
object_columns:
- room_type_reserved
- booking_status

# Predictors and label related
label: booking_status
predictors:
- no_of_adults
- no_of_children
- no_of_weekend_nights
- no_of_week_nights
- required_car_parking_space
- lead_time
- arrival_year
- arrival_month
- arrival_date
- repeated_guest
- no_of_previous_cancellations
- no_of_previous_bookings_not_canceled
- no_of_special_requests
- avg_price_per_room
- room_type_reserved


# Range of data related

range_no_of_adults:
- 0
- 4
range_no_of_children:
- 0
- 10
range_no_of_weekend_nights:
- 0
- 7
range_no_of_week_nights:
- 0
- 17
range_lead_time:
- 0
- 1500
range_required_car_parking_space:
- 0
- 1
range_arrival_year:
- 2017
- 2018
range_arrival_month:
- 1
- 12
range_arrival_date:
- 1
- 31
range_repeated_guest:
- 0
- 1
range_no_of_previous_cancellations:
- 0 
- 14
range_no_of_previous_bookings_not_canceled:
- 0
- 60
range_avg_price_per_room:
- 0
- 540
range_no_of_special_requests:
- 0
- 5
range_room_type_reserved:
- Room_Type 1
- Room_Type 4
- Room_Type 2
- Room_Type 6
- Room_Type 5
- Room_Type 7
- Room_Type 3
range_booking_status:
- Canceled
- Not_Canceled